# Generated by Django 3.1.5 on 2021-02-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210202_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='person',
            new_name='user',
        ),
    ]
